eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:9089/eureka
    instance:
        prefer-ip-address: true
